version: '3'
services:
  app:
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - CSCI_SALT=${CSCI_SALT}
    build:
      context: .

    volumes:
      - .:/app
