channels:
- defaults
- bokeh
- conda-forge
dependencies:
- matplotlib
- nbconvert
- numpy
- pandas
- scipy
- seaborn
- scikit-learn
- dask
- dask-ml
- jupyter
- jupyterlab
- tenacity
- botocore
- boto3

- pip:
  - apache-airflow
